FROM node:21-bookworm-slim
LABEL maintainer="sinfallas@gmail.com"

WORKDIR /opt/opendevin
RUN apt-get update && apt -y install rust-all nodejs npm docker.io containerd git
RUN git clone https://github.com/OpenDevin/OpenDevin.git /opt/opendevin
RUN cd frontend && npm install
COPY entrypoint_backend.sh .
EXPOSE 3001
CMD ["bash","/opt/opendevin/entrypoint.sh"]
